#1416: make tranform not forget about `StringLiteral`s
dsherret/ts-simple-ast pull request #1417
Opened 2023-06-13 18:15 UTC by ivanhofer

closes #1416

2023-06-13 18:16 UTC, ivanhofer commented
A test fails. Somehow the changed code breaks something with JSDoc comments. Not sure how to fix this.
The fix sometimes also outputs the code with another formatting.

2023-06-14 22:45 UTC, dsherret requested changes
This seems pretty reasonable to do actually. Just needs to fallback to using the initial source file I think.

2023-06-14 22:45 UTC, dsherret commented on packages/ts-morph/src/compiler/ast/common/Node.ts
> +          finalText += printer.printNode(ts.EmitHint.Unspecified, transform.compilerNode, transform.compilerNode.getSourceFile());
```suggestion
          finalText += printer.printNode(ts.EmitHint.Unspecified, transform.compilerNode, transform.compilerNode.getSourceFile() ?? compilerSourceFile);
```

It probably needs to be this.

2023-06-14 22:48 UTC, dsherret commented on packages/ts-morph/src/compiler/ast/common/Node.ts
> +          finalText += printer.printNode(ts.EmitHint.Unspecified, transform.compilerNode, transform.compilerNode.getSourceFile());
Actually, it looks like the initial code was wrong...

2023-06-14 22:54 UTC, dsherret commented on packages/ts-morph/src/compiler/ast/common/Node.ts
> +          finalText += printer.printNode(ts.EmitHint.Unspecified, transform.compilerNode, transform.compilerNode.getSourceFile());
No, ok I remember it now. This suggestion was correct.

2023-06-14 22:54 UTC, dsherret approved these changes
LGTM. Thanks!

2023-06-14 22:55 UTC, merged